theme = "hugo-now-ui"
baseurl = "/"
relativeurls = true
languageCode = "ca-es"
title = "Webmentors"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Principal"
    url = "/principal"
    pre = "<i class='now-ui-icons business_bank'></i>"
    weight = 1
[[menu.main]]
    name = "Cicles d'Informàtica"
    url = "/cicles"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2
[[menu.main]]
    name = "Edicions"
    pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
    url = "#"
    weight = 4
    identifier = "dropdown"
[[menu.main]]
    name = "1a. Edicio (2017)"
    pre = "<i class='now-ui-icons files_paper'></i>"
    url = "/2017/template"
    weight = 1
    parent = "dropdown"
[[menu.main]]
    name = "2a. Edicio (2018)"
    pre = "<i class='now-ui-icons files_paper'></i>"
    url = "/2018/template"
    weight = 2
    parent = "dropdown"

[[menu.main]]
    name = "Notícies"
    pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
    url = "/post"
    weight = 5



[params]
    background = "img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


